# -*- coding: utf-8 -*-
"""Analisis_Sentimientos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o8BawVYz4-MwpEpev2O5PcnIujynf-8z
"""

from google.colab import drive
drive.mount('/content/drive')

"""
Realizado por Sergio Andres Cobos Suarez, ID: 668851
"""

import pandas as pd
from textblob import TextBlob
import seaborn as sns

"""
Aquí se debe colocar el archivo CommentsMarch2018.csv, el cual va adjunto con el codigo
"""
df=pd.read_csv('/content/drive/MyDrive/SENTIMIENTOS/CommentsMarch2018.csv')

df['polaridad']=df['commentBody'].apply(lambda x: TextBlob(x).sentiment.polarity)
print(df['polaridad'].head(5))

df['subobj']=df['commentBody'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

print("Polaridad")
print("Maximo valor ", df['polaridad'].max())
print("Minimo valor ", df['polaridad'].min())
print("Valor Promedio", df['polaridad'].mean())

sns.distplot(df['polaridad'])

sns.distplot(df['subobj'])

n=1
while n<5:
  df['P ' +str(n)]=df['commentBody'].apply(lambda x: TextBlob(x).sentiment.polarity)
  df['S ' +str(n)]=df['commentBody'].apply(lambda x: TextBlob(x).sentiment.subjectivity)
  n=n+1

import re
def clean_text(text):
  text = re.sub(r'#', '', text)
  text = re.sub(r'@[A-Za-z0-9]+', '', text)
  return text

df['clean_text'] = df['commentBody'].apply(clean_text)
df['clean_text']

df['polaridad']=df['clean_text'].apply(lambda x: TextBlob(x).sentiment.polarity)

def x_range(x):
  if x>0:
    return 1
  elif x == 0:
      return 0
  else:
      return -1

df['resultado']= df['polaridad'].apply(x_range)

df['resultado'].value_counts()

import matplotlib.pyplot as plt
labels = 'Neutro', 'Positivo', 'Negativo'
colors = ['#29A0B1','#167D7F','#98D7C2']
plt.pie(df['resultado'].value_counts(), labels = labels, colors = colors,
        autopct = '%1.1f%%', shadow = True, startangle = 90)
plt.title('Sentimientos', fontsize = 20)
plt.axis('equal')
plt.show()

!pip install WordCloud
from wordcloud import WordCloud
text = ' '.join(df.clean_text)
text

wordcloud = WordCloud(width=1024, height=800, colormap='Blues', min_font_size=14).generate(text)

plt.figure(figsize= (8, 8), facecolor=None)
plt.imshow(wordcloud)
plt.axis('off')
plt.tight_layout(pad=0)
plt.show()